#!/bin/bash
#
# Docker + Portainer + Let's Encrypt
#
# IMPORTANT: Once deployed, visit https://{host}:9000 to change the default admin password!
# 
# <UDF name="user_name" label="Unprivileged User Account" />
# <UDF name="user_password" label="Unprivileged User Password" />
# <UDF name="user_sshkey" label="RSA Public Key (Recommended)" />
#
# <UDF name="hostname" label="Hostname" example="Example: docker01" />
# <UDF name="fqdn" label="Fully Qualified Domain Name (FQDN)" example="Example: docker01.mydomain.com" />
# <UDF name="enable_le" label="Use Let's Encrypt to manage Portainer's HTTPS certificate? (Y/n)" default="Y" />
# <UDF name="letsencrypt_email" label="E-mail address for Let's Encrypt" default="sdavis@nativeit.net" />
# <UDF name="tz" label="Time Zone" default="America/New_York" example="Example: America/New_York (see: http://bit.ly/TZlisting)" />
#
# <UDF name="sshd_port" label="SSH Port" default="22" />
# <UDF name="sshd_protocol" label="SSH Protocol (Default is '2')" oneOf="1,2,1 and 2" default="2" />
# <UDF name="sshd_permitroot" label="SSH Permit Root Login (Default is 'no')" oneof="No,Yes" default="No" />
# <UDF name="sshd_passwordauth" label="SSH Password Authentication (Default is 'no')" oneOf="No,Yes" default="No" />
# <UDF name="sshd_group" label="SSH Allowed Groups (Default is 'sshusers')" default="sshusers" example="List of groups seperated by spaces" />
# <UDF name="sudo_usergroup" label="Admin Usergroup (Default is 'wheel')" default="wheel" />
# <UDF name="sudo_passwordless" label="Passwordless Sudo (Not Recommended)" oneof="Require Password,Do Not Require Password", default="Require Password" />
# Include Linode BASH Library from https://cloud.linode.com/stackscripts/1
source <ssinclude StackScriptID=1>
# Variables
IPADDR=$(/sbin/ifconfig eth0 | awk '/inet / { print $2 }' | sed 's/addr://')
# Set timezone
if [ -n $TZ ]
then
  timedatectl set-timezone $TZ
fi
# Update repositories and system packages
echo "###################################################################################"
echo "Please be Patient: Installation will start now....... It may take some time :)"
echo "###################################################################################"
apt update
DEBIAN_FRONTEND=noninteractive apt upgrade -y
# Set the hostname & add fully-qualified domain name (FQDN) in hosts file
echo $HOSTNAME > /etc/hostname
hostname -F /etc/hostname
if [ -n $FQDN ]
then
  echo $IPADDR $FQDN $HOSTNAME >> /etc/hosts
else
  echo $IPADDR $HOSTNAME >> /etc/hosts
fi
# Install dependencies
apt install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
apt-get -y install aptitude
aptitude -y install net-tools
aptitude -y install apt-transport-https
# Setup sudo
aptitude -y install sudo
cp /etc/sudoers /etc/sudoers.tmp
chmod 0640 /etc/sudoers.tmp
test "${SUDO_PASSWORDLESS}" == "Do Not Require Password" && (echo "%`echo ${SUDO_USERGROUP} | tr '[:upper:]' '[:lower:]'` ALL = NOPASSWD: ALL" >> /etc/sudoers.tmp)
test "${SUDO_PASSWORDLESS}" == "Require Password" && (echo "%`echo ${SUDO_USERGROUP} | tr '[:upper:]' '[:lower:]'` ALL = (ALL) ALL" >> /etc/sudoers.tmp)
chmod 0440 /etc/sudoers.tmp
mv /etc/sudoers.tmp /etc/sudoers
# Create Groups
groupadd ${SSHD_GROUP}
groupadd ${SUDO_USERGROUP}
# Create User & Add SSH Key
USER_NAME_LOWER=`echo ${USER_NAME} | tr '[:upper:]' '[:lower:]'`
useradd -m -s /bin/bash -G ${SSHD_GROUP},${SUDO_USERGROUP} ${USER_NAME_LOWER}
echo "${USER_NAME_LOWER}:${USER_PASSWORD}" | chpasswd
USER_HOME=`sed -n "s/${USER_NAME_LOWER}:x:[0-9]*:[0-9]*:[^:]*:\(.*\):.*/\1/p" < /etc/passwd`
sudo -u ${USER_NAME_LOWER} mkdir ${USER_HOME}/.ssh
echo "${USER_SSHKEY}" >> $USER_HOME/.ssh/authorized_keys
chmod 0600 $USER_HOME/.ssh/authorized_keys
chown ${USER_NAME_LOWER}:${USER_NAME_LOWER} $USER_HOME/.ssh/authorized_keys
# Configure SSHD
echo "Port ${SSHD_PORT}" > /etc/ssh/sshd_config.tmp
echo "Protocol ${SSHD_PROTOCOL}" >> /etc/ssh/sshd_config.tmp
echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config.tmp
sed -n 's/\(HostKey .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(UsePrivilegeSeparation .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(KeyRegenerationInterval .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(ServerKeyBits .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(SyslogFacility .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(LogLevel .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(LoginGraceTime .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
echo "PermitRootLogin `echo ${SSHD_PERMITROOT} | tr '[:upper:]' '[:lower:]'`" >> /etc/ssh/sshd_config.tmp
sed -n 's/\(StrictModes .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(RSAAuthentication .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(IgnoreRhosts .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(RhostsRSAAuthentication .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(HostbasedAuthentication .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(PermitEmptyPasswords .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(ChallengeResponseAuthentication .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
echo "PasswordAuthentication `echo ${SSHD_PASSWORDAUTH} | tr '[:upper:]' '[:lower:]'`" >> /etc/ssh/sshd_config.tmp
sed -n 's/\(X11Forwarding .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(X11DisplayOffset .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(PrintMotd .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(PrintLastLog .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(TCPKeepAlive .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(MaxStartups .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(AcceptEnv .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(Subsystem .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
sed -n 's/\(UsePAM .*\)/\1/p' < /etc/ssh/sshd_config >> /etc/ssh/sshd_config.tmp
echo "AllowGroups `echo ${SSHD_GROUP} | tr '[:upper:]' '[:lower:]'`" >> /etc/ssh/sshd_config.tmp
chmod 0600 /etc/ssh/sshd_config.tmp
cp /etc/ssh/sshd_config.tmp /etc/ssh/sshd_config
touch /tmp/restart-ssh
# Install Docker
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
apt update
apt-cache policy docker-ce
apt install -y docker-ce
# Generate TLS certificates via Let's Encrypt for Portainer
apt update && apt install certbot -y
if [ -n $LETSENCRYPT_EMAIL ] && [ -n $FQDN ] && [ "${ENABLE_LE,,}" = 'y' ] && [ "${ENABLE_WWW,,}" = 'y' ]
then
  certbot certonly --standalone --preferred-challenges http --email "${LETSENCRYPT_EMAIL}" --noninteractive --quiet --agree-tos -d $FQDN -d www.$FQDN
elif [ -n $LETSENCRYPT_EMAIL ] && [ -n $FQDN ] && [ "${ENABLE_LE,,}" = 'y' ]
then
  certbot certonly --standalone --preferred-challenges http --email "${LETSENCRYPT_EMAIL}" --noninteractive --quiet --agree-tos -d $FQDN
fi
if [ "${ENABLE_LE,,}" = 'y' ]
then
  cat <(crontab -l) <(echo "0 1,13 * * * certbot renew") | crontab -
fi
# Install Portainer
docker run -d -p 9000:9000 --restart unless-stopped --name portainer \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-v /root/portainer/data:/data \
	-v /etc/letsencrypt/live/$FQDN:/certs/live/$FQDN:ro \
	-v /etc/letsencrypt/archive/$FQDN:/certs/archive/$FQDN:ro \
	portainer/portainer --ssl --sslcert /certs/live/$FQDN/cert.pem --sslkey /certs/live/$FQDN/privkey.pem
# Install ctop: https://github.com/bcicen/ctop
wget https://github.com/bcicen/ctop/releases/download/v0.7/ctop-0.7-linux-amd64 -O /usr/local/bin/ctop
chmod +x /usr/local/bin/ctop
# Install UFW
aptitude -y install ufw
# Set firewall ports for Portainer & CapRover
ufw allow 53,80,443,3000,996,7946,4789,2377/tcp
ufw allow 53,7946,4789,2377/udp
# Wrap it up
automatic_security_updates
goodstuff
all_set
restartServices
