#!/bin/bash
#
# Debian 10 w/basic setup, security, postfix gmail relay, openjdk8, Docker, Caprover
# Copyright (c) 2020 Native IT
#
# IMPORTANT: Once deployed, visit https://{host}:9000 to change the default admin password!
# 
# <UDF name="user1_name" label="User 1 account name" example="This is the account that you will be using to log in." />
# <UDF name="user1_password" label="User 1 password" />
# <UDF name="user1_group" label="Add'l group for user 1" default="" />
# <UDF name="user1_shell" label="Shell" oneof="/bin/zsh,/bin/bash" default="/bin/bash" />
#
# <UDF name="user1_sshkey" label="Public Key for user 1" default="" example="Recommended method of authentication. It is more secure than password log in." />
# <UDF name="sshd_port" label="SSH Listening Port" default="22" />
# <UDF name="domain" label="System domain name" default="example.com" example="Domain w/out hostname" />
# <UDF name="fqdn" label="Fully Qualified Domain Name" />
# <UDF name="enable_le" label="Use Let's Encrypt to manage Portainer's HTTPS certificate? (Y/n)" default="Y" />
# <UDF name="letsencrypt_email" label="E-mail address for Let's Encrypt" default="sdavis@nativeit.net" />
# <UDF name="enable_www" label="Add additional 'www.' domain? (y/N)" default="N" />
# <UDF name="tz" label="Time Zone" default="America/New_York" example="Example: America/New_York (see: http://bit.ly/TZlisting)" />
# <UDF name="relay_email" label="Gmail email including domain as relay" example="Email used to login into Gmail/GApps" />
# <UDF name="relay_password" label="Gmail account app-specific password" example="Email account password (app specific with 2factor auth)" />

# Setup "Unofficial Bash Strict Mode" -- http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -e # Exit immediately on error
set -u # Throw error on undefined variable
#set -x # Uncomment to enable debugging

exec &> /root/stackscript.log

set +u

source <ssinclude StackScriptID="1"> # StackScript Bash Library
#source ./linode-ss1.sh

source <ssinclude StackScriptID="691666"> # lib-system-utils
#source ./lib-system-utils.sh

source <ssinclude StackScriptID="691674"> # lib-system-debian
#source ./lib-system-debian.sh

set -u

# Set variables
IPADDR=$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
NOTIFY_EMAIL=$LETSENCRYPT_EMAIL

echo "###################################################################################"
echo "Please be Patient: Installation will start now....... It may take some time :)"
echo "###################################################################################"

###########################################################
# System setup
###########################################################

system_primary_ip
system_primary_ipv6

# Extend /etc/apt/sources.list
system_enable_extended_sources

# Set timezone
system_set_timezone "$TZ"

# Setup /etc versioning
system_install_git
system_start_etc_dir_versioning 

# Initialize hostname
system_set_hostname "$FQDN"
system_record_etc_dir_changes "Updated hostname" 

# Update /etc/hosts
system_update_hosts "$IPADDR" "$FQDN"

# Setup NTP
system_configure_ntp

###########################################################
# User & Security
###########################################################

# Create user accounts
system_add_user "$USER1_NAME" "$USER1_PASSWORD" "$USER1_GROUP" "$USER1_SHELL"
if [ "$USER1_SSHKEY" ]; then
    system_user_add_ssh_key "$USER1_NAME" "$USER1_SSHKEY"
fi
system_record_etc_dir_changes "Added sudo user account"

# Setup user profile preferences
system_pimp_user_profiles "$USER1_NAME"
system_record_etc_dir_changes "Added custom bash profile settings." 

# Configure SSHD
system_configure_sshd "USER1_SSHKEY" "SSHD_PORT"
system_record_etc_dir_changes "Configured SSH for key authentication and custom port." 

# Setup logcheck
system_security_logcheck
system_record_etc_dir_changes "Installed logcheck" 

# Setup fail2ban
system_security_fail2ban
system_record_etc_dir_changes "Installed fail2ban"

# Install UFW
system_security_ufw_install
system_record_etc_dir_changes "Installed UFW"

# Setup UFW
system_security_ufw_configure_advanced
system_record_etc_dir_changes "Setup UFW with ports for Docker, Portainer, Virtualmin, SSH"

###########################################################
# Software & Utilities
###########################################################

# Install basic system utilities
system_install_utils
system_install_java8
system_record_etc_dir_changes "Installed common utils"

# Install Postfix
postfix_install_gmail_relay
system_record_etc_dir_changes "Installed postfix gmail relay" 

# Install Docker + Docker Compose
system_install_docker
curl -L "https://github.com/docker/compose/releases/download/1.28.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

# Generate TLS certificates via Let's Encrypt for Portainer
apt update && apt install certbot -y
if [ -n $LETSENCRYPT_EMAIL ] && [ -n $FQDN ] && [ "${ENABLE_LE,,}" = 'y' ] && [ "${ENABLE_WWW,,}" = 'y' ]
then
  certbot certonly --standalone --preferred-challenges http --email "${LETSENCRYPT_EMAIL}" --noninteractive --quiet --agree-tos -d $FQDN -d www.$FQDN
elif [ -n $LETSENCRYPT_EMAIL ] && [ -n $FQDN ] && [ "${ENABLE_LE,,}" = 'y' ]
then
  certbot certonly --standalone --preferred-challenges http --email "${LETSENCRYPT_EMAIL}" --noninteractive --quiet --agree-tos -d $FQDN
fi
if [ "${ENABLE_LE,,}" = 'y' ]
then
  cat <(crontab -l) <(echo "0 1,13 * * * certbot renew") | crontab -
fi

# Create portainer_data volume
mkdir /usr/share/portainer_data
docker volume create portainer_data
chmod 0755 /usr/share/portainer_data

# Setup admin password
echo -n $USER1_PASSWORD > /tmp/portainer_password

# Install Portainer
docker run -d -p 9000:9000 --restart unless-stopped --name portainer \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-v /usr/share/portainer_data:/data \
    -v /tmp/portainer_password:/tmp/portainer_password \
	-v /etc/letsencrypt/live/$FQDN:/certs/live/$FQDN:ro \
	-v /etc/letsencrypt/archive/$FQDN:/certs/archive/$FQDN:ro \
	portainer/portainer-ce \
  --admin-password-file /tmp/portainer_password \
  --ssl --sslcert /certs/live/$FQDN/cert.pem --sslkey /certs/live/$FQDN/privkey.pem
system_record_etc_dir_changes "Setup Portainer Docker container"

# Install ctop: https://github.com/bcicen/ctop
wget https://github.com/bcicen/ctop/releases/download/v0.7/ctop-0.7-linux-amd64 -O /usr/local/bin/ctop
chmod +x /usr/local/bin/ctop

# Install Caprover
IPADDR=$(/sbin/ifconfig eth0 | awk '/inet / { print $2 }' | sed 's/addr://')
cat << EOF > /tmp/caprover.json
    {"caproverIP": "$IPADDR", "caproverPassword": "$USER1_PASSWORD", "caproverRootDomain": "$DOMAIN", "newPassword": "$USER1_PASSWORD", "certificateEmail": "$LETSENCRYPT_EMAIL", "caproverName": "captain-ntv"}
EOF
docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock -v /captain:/captain caprover/caprover
npm install -g caprover
caprover serversetup -c /tmp/caprover.json

# Retain log after reboot
system_configure_persistent_journal
system_record_etc_dir_changes "Configure persistent journal"

# Send info message
cat > ~/setup_message <<EOD
Hi,

Your Linode VPS configuration is completed. You may access Portainer at https://$FQDN:9000 or Caprover at https://$FQDN:3000.

EOD

mail -s "Your Linode VPS $FQDN is ready" "$NOTIFY_EMAIL" < ~/setup_message

# Install Virtualmin
system_install_virtualmin
sed -i"" -e "s/port=10000/port=4242/" /etc/webmin/miniserv.conf
touch /tmp/restart_initd-webmin

# System updates
debian_upgrade
system_update

# Wrap it up
automatic_security_updates
goodstuff
restart_services
restart_initd_services
all_set
stackscript_cleanup
